# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('geocron-example', ['geocron'])
    obj.source = 'geocron-example.cc'
    obj.lib = ['boost_system', 'boost_filesystem'] #needed for scratch to use boost libs
