# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def get_all_sources(path):
    import os.path
    
    sources = []
    headers = []

    # we want to save relative filenames from src/$MODULE_NAME/

    for d in [os.path.join(path,d2) for d2 in ['model',
                                               #'helper',
                                               #'model/heuristics'
                                               ]]:
        files = [os.path.join(d, f) for f in os.listdir(d)]
        sources.extend([os.path.relpath(f,path) for f in files if f.endswith('.cc') and not (os.path.isdir(f) or '#' in f)])
        headers.extend([os.path.relpath(f,path) for f in files if f.endswith('.h') and not (os.path.isdir(f) or '#' in f)])

    return sources, headers

def build(bld):
    module = bld.create_ns3_module('geocron', ['core', 'network', 'internet', 'applications', 'mobility', 'nix-vector-routing', 'topology-read', 'point-to-point', 
        'brite',
        #these only needed for Test Suite
        'point-to-point-layout'
        ])
    module.lib = ['boost_system', 'boost_filesystem'] #needed to use boost libs

    module.source, headers_list = get_all_sources(bld.path.relpath())

    module_test = bld.create_ns3_module_test_library('geocron')
    module_test.source = [
        'test/geocron-test-suite.cc',
        ]
    
    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'geocron'
    headers.source = headers_list

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

